FROM python:3.5.2-alpine

RUN apk add -vv --no-cache --virtual .build_deps \
        build-base \
        linux-headers \
        && \
    # pip install --no-cache-dir foo_bar && \
    # apk del .build_deps && \
    # rm -rf /tmp/* /var/tmp/* /var/cache/apk/* /root/.cache/pip/* && \ 
    echo done.

